### ISSUE TITLE
Unread posts missing when they occupy more than one page

### ISSUE THREAD

**Issue by Ezerous** [ThmmyNoLife/mTHMMY#1]
Only posts from the first page are fetched.

**Comment by Thodoris1999** [comment]
How are only the post from the first page fetched? Doesn't clicking on unread posts launch a topic activity? I thought all posts are fetched from a topic anyways.

Are there any steps to reproduce this?

**Comment by Ezerous** [comment]
All posts in Unread tab are fetched from [https://www.thmmy.gr/smf/index.php?action=unread](https://www.thmmy.gr/smf/index.php?action=unread). If by any chance you have more than one page of them (using a browser), then you won't see those pages in the app.

**Comment by Apostolof** [comment]
Working on it...

**Comment by Apostolof** [comment]
Fixed with 3f1cce8d00fadd86e65c2137171ea72dfbb44215
