### ISSUE TITLE
Post attachments need to be clicked twice for download to start

### ISSUE THREAD

**Issue by Ezerous** [ThmmyNoLife/mTHMMY#10]
To reproduce go to a topic with attachments and **before** clicking anything else click to an attachment. Nothing will happen (onClickListener will not be triggered), however upon clicking for a second time the download will start normally.

**Comment by Apostolof** [comment]
This may be originating from the checkPerms() function.

**Comment by Ezerous** [comment]
> 
> 
> This may be originating in the checkPerms() function.

Not at all.

This was related to https://stackoverflow.com/questions/46452465/android-the-item-inside-recyclerview-cant-be-clicked-after-scroll, and actually affected everything inside the CardViews. Fixed with a custom RecyclerView in https://github.com/ThmmyNoLife/mTHMMY/commit/5fe9af78f9540a3cafaa2c7b2ac33e43e922b2d6. Note that this RecyclerView is not needed in LatestPostsFragment, because no other ScrollAware Behaviors exist to steal the touch events.
