### ISSUE TITLE
Integrate eTHMMY RSS feeds

### ISSUE THREAD

**Issue by Apostolof** [ThmmyNoLife/mTHMMY#15]
Integrate the RSS feed system found [here](https://github.com/spapageo/ethmmyrss), or something similar, so that users can choose from the list of courses that are in eThmmy and receive notifications of new announcements.

**Comment by Ezerous** [comment]
Can also integrate [http://ee.auth.gr/feed/](http://ee.auth.gr/feed/) feeds.

**Comment by Apostolof** [comment]
Not needed after all. The platform will be discontinued in the next semester.
Maybe something similar could be done for elearning, the courses are migrating to.
