### ISSUE TITLE
Notifications break on Android 5

### ISSUE THREAD

**Issue by Apostolof** [ThmmyNoLife/mTHMMY#17]
On android 5 notification icon isn't properly displayed and the text is missing.

![screenshot](https://user-images.githubusercontent.com/23389443/42313849-5b6101b8-804c-11e8-9b80-ac51a46fc85f.png)

The icon problem and solution are discussed here:
https://github.com/nextcloud/news-android/issues/348
https://clevertap.com/blog/fixing-notification-icon-for-android-lollipop-and-above/

The solution cannot be applied well to our logo, because of shadows. Maybe a new, separate, simpler design specifically for the notifications is the best approach here.

**Comment by Ezerous** [comment]
Closed with https://github.com/ThmmyNoLife/mTHMMY/commit/43deae2d38554772a66826df2729e51eb994f5d7
