### ISSUE TITLE
Crash details do not appear on Firebase console

### ISSUE THREAD

**Issue by Ezerous** [ThmmyNoLife/mTHMMY#41]
[CrashreportingTree]( https://github.com/ThmmyNoLife/mTHMMY/blob/develop/app/src/main/java/gr/thmmy/mthmmy/utils/CrashReportingTree.java ) class uses  Crashlytics.log() to forward Timber messages to Firebase. However, when attempting to view the detailed log of a crash on the Firebase console, no such messages seem to be logged.

**Comment by Thodoris1999** [comment]
resolved in #46
