### ISSUE TITLE
Double notifications

### ISSUE THREAD

**Issue by Thodoris1999** [ThmmyNoLife/mTHMMY#58]
If a user has bookmarked a board and one of its subboards, he gets double notifications for new posts in the subboard.

**Comment by Ezerous** [comment]
The fix also requires intervention in the backend. Till then, users can simply disable the notifications in the subboard.

**Comment by Ezerous** [comment]
Fixed in https://github.com/ThmmyNoLife/mTHMMY/commit/46de365f7b77df9ef56d3b324a9b4c4bda5f183f
