### ISSUE TITLE
Load last page when user wants to reply to a topic

### ISSUE THREAD

**Issue by Ezerous** [ThmmyNoLife/mTHMMY#7]
Reply's text box now appears on the current page.

**Comment by Apostolof** [comment]
Some work was done at 6642910f09ecafe88897d74e5ae7b0bb996e5f47, but a bug occured where the app crashes when you have quoted messages and press reply at a page other than the last one.

@Thodoris1999 has a solution ready, so the issue will be closed when the fix is pushed.

**Comment by Thodoris1999** [comment]
It is solved in this PR since the code is very different: https://github.com/ThmmyNoLife/mTHMMY/pull/34

**Comment by Apostolof** [comment]
PR was merged, closing issue.
